[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = [
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests -U"
]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -Xmx512m -Xms256m -jar target/*.jar"
